// ─── Furniture Catalog ─────────────────────────────────────
// Central catalog of furniture items with placeholder asset URLs.
// Used by the client for rendering and by matchCatalogItem() for
// fuzzy-matching Gemini-detected item names to known catalog entries.
import {
  getDefaultFurniturePreviewUrl,
  type FurnitureAssetManifestEntry,
  type FurnitureAssetOrigin,
} from "./furniture-assets.js";
import type {
  AssetProvenance,
  BimReference,
  CatalogMaterialSlot,
} from "./material-library.js";

const ASSET_BASE = "/assets/furniture";

export interface CatalogItem extends FurnitureAssetManifestEntry {
  thumbnailUrl: string | null;
}

type CatalogItemSeed = Omit<
  CatalogItem,
  | "thumbnailUrl"
  | "previewUrl"
  | "bounds"
  | "origin"
  | "qualityTier"
  | "styleTier"
  | "materialSlots"
  | "provenance"
  | "bimRef"
  | "performanceBudgetKb"
> &
  Partial<
    Pick<
      CatalogItem,
      | "thumbnailUrl"
      | "previewUrl"
      | "bounds"
      | "origin"
      | "qualityTier"
      | "styleTier"
      | "materialSlots"
      | "provenance"
      | "bimRef"
      | "performanceBudgetKb"
    >
  >;

function getDefaultMaterialSlots(category: CatalogItem["category"]): CatalogMaterialSlot[] {
  switch (category) {
    case "bathroom":
      return [{ slotId: "primary", label: "Primary finish", finishId: "item-stone", finishVariantId: "travertine" }];
    case "kitchen":
      return [{ slotId: "primary", label: "Primary finish", finishId: "item-stone", finishVariantId: "ash" }];
    case "office":
      return [{ slotId: "primary", label: "Primary finish", finishId: "item-oak", finishVariantId: "smoked" }];
    default:
      return [{ slotId: "primary", label: "Primary finish", finishId: "item-oak", finishVariantId: "natural" }];
  }
}

function withCatalogDefaults(item: CatalogItemSeed): CatalogItem {
  const previewUrl = item.previewUrl ?? item.thumbnailUrl ?? getDefaultFurniturePreviewUrl(item.id);
  const bounds = item.bounds ?? { ...item.dimensions };
  const origin: FurnitureAssetOrigin = item.origin ?? { x: 0.5, y: 0, z: 0.5 };
  const provenance: AssetProvenance = item.provenance ?? {
    source: "internal",
    license: "Unspecified",
  };
  const bimRef: BimReference = item.bimRef ?? {
    source: "catalog",
    externalId: item.id,
  };
  const materialSlots = item.materialSlots ?? getDefaultMaterialSlots(item.category);

  return {
    ...item,
    previewUrl,
    thumbnailUrl: previewUrl,
    bounds,
    origin,
    qualityTier: item.qualityTier ?? "placeholder",
    styleTier: item.styleTier ?? "realistic",
    materialSlots,
    provenance,
    bimRef,
    performanceBudgetKb: item.performanceBudgetKb ?? 500,
  };
}

const FURNITURE_CATALOG_SEED: CatalogItemSeed[] = [
  // ── Living ──────────────────────────────────────────────
  {
    id: "sofa-01",
    name: "Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.2, y: 0.85, z: 0.9 },
    keywords: ["sofa", "couch", "settee", "loveseat", "seating"],
  },
  {
    id: "armchair-01",
    name: "Armchair",
    category: "living",
    modelUrl: `${ASSET_BASE}/armchair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 0.85, z: 0.9 },
    keywords: ["armchair", "arm chair", "accent chair", "lounge chair", "easy chair"],
  },
  {
    id: "coffee-table-01",
    name: "Coffee Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/coffee-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.45, z: 0.6 },
    keywords: ["coffee table", "center table", "cocktail table", "low table"],
  },
  {
    id: "tv-stand-01",
    name: "TV Stand",
    category: "living",
    modelUrl: `${ASSET_BASE}/tv-stand-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.5, z: 0.4 },
    keywords: ["tv stand", "tv unit", "tv cabinet", "entertainment center", "media console"],
  },
  {
    id: "bookshelf-01",
    name: "Bookshelf",
    category: "living",
    modelUrl: `${ASSET_BASE}/bookshelf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 1.8, z: 0.35 },
    keywords: ["bookshelf", "bookcase", "shelf", "shelving", "book case", "shelves"],
  },

  // ── Bedroom ─────────────────────────────────────────────
  {
    id: "bed-double-01",
    name: "Double Bed",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bed-double-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.6, y: 0.5, z: 2.0 },
    keywords: ["double bed", "queen bed", "king bed", "bed"],
  },
  {
    id: "bed-single-01",
    name: "Single Bed",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bed-single-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 0.5, z: 2.0 },
    keywords: ["single bed", "twin bed", "cot"],
  },
  {
    id: "nightstand-01",
    name: "Nightstand",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/nightstand-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.55, z: 0.4 },
    keywords: ["nightstand", "night stand", "bedside table", "night table", "side table"],
  },
  {
    id: "wardrobe-01",
    name: "Wardrobe",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/wardrobe-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 2.2, z: 0.6 },
    keywords: ["wardrobe", "closet", "armoire", "cupboard"],
  },
  {
    id: "desk-01",
    name: "Desk",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/desk-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.75, z: 0.6 },
    keywords: ["desk", "writing desk", "study desk", "workstation", "work desk"],
  },

  // ── Kitchen ─────────────────────────────────────────────
  {
    id: "fridge-01",
    name: "Refrigerator",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/fridge-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.7, y: 1.8, z: 0.7 },
    keywords: ["fridge", "refrigerator", "freezer", "icebox"],
  },
  {
    id: "oven-01",
    name: "Oven",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/oven-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["oven", "stove", "range", "cooktop", "cooker"],
  },
  {
    id: "dining-table-01",
    name: "Dining Table",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/dining-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.6, y: 0.75, z: 0.9 },
    keywords: ["dining table", "kitchen table", "table", "eating table"],
  },
  {
    id: "dining-chair-01",
    name: "Dining Chair",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/dining-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.9, z: 0.45 },
    keywords: ["dining chair", "kitchen chair", "chair"],
  },
  {
    id: "sink-kitchen-01",
    name: "Kitchen Sink",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/sink-kitchen-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.2, z: 0.5 },
    keywords: ["kitchen sink", "sink", "basin"],
  },

  // ── Bathroom ────────────────────────────────────────────
  {
    id: "toilet-01",
    name: "Toilet",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/toilet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.4, z: 0.65 },
    keywords: ["toilet", "wc", "water closet", "commode", "lavatory"],
  },
  {
    id: "bathtub-01",
    name: "Bathtub",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/bathtub-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.75, y: 0.6, z: 1.7 },
    keywords: ["bathtub", "bath", "tub"],
  },
  {
    id: "shower-01",
    name: "Shower",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/shower-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 2.1, z: 0.9 },
    keywords: ["shower", "shower stall", "shower cabin", "shower enclosure"],
  },
  {
    id: "vanity-01",
    name: "Bathroom Vanity",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/vanity-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.85, z: 0.5 },
    keywords: ["bathroom vanity", "vanity", "bathroom sink", "washbasin", "basin", "wash basin", "basin cabinet"],
  },

  // ── Office ──────────────────────────────────────────────
  {
    id: "office-desk-01",
    name: "Office Desk",
    category: "office",
    modelUrl: `${ASSET_BASE}/office-desk-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.75, z: 0.7 },
    keywords: ["office desk", "work desk", "computer desk", "writing desk", "study desk", "workstation"],
  },
  {
    id: "office-chair-01",
    name: "Office Chair",
    category: "office",
    modelUrl: `${ASSET_BASE}/office-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 1.1, z: 0.6 },
    keywords: ["office chair", "task chair", "swivel chair", "ergonomic chair"],
  },

  // ── Living (additional) ───────────────────────────────────
  {
    id: "modern-sofa-01",
    name: "Modern Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/modern-sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.0, y: 0.75, z: 0.85 },
    keywords: ["modern sofa", "design sofa", "contemporary sofa"],
  },
  {
    id: "modern-chair-01",
    name: "Modern Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/modern-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.75, z: 0.8 },
    keywords: ["modern chair", "design chair", "accent chair"],
  },
  {
    id: "corner-sofa-01",
    name: "Corner Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/corner-sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.5, y: 0.85, z: 2.5 },
    keywords: ["corner sofa", "sectional sofa", "l-shaped sofa", "sectional"],
  },
  {
    id: "glass-coffee-table-01",
    name: "Glass Coffee Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/glass-coffee-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.1, y: 0.4, z: 0.55 },
    keywords: ["glass coffee table", "glass table"],
  },
  {
    id: "round-table-01",
    name: "Round Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/round-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.75, z: 1.0 },
    keywords: ["round table", "circular table", "bistro table"],
  },
  {
    id: "television-01",
    name: "Television",
    category: "living",
    modelUrl: `${ASSET_BASE}/television-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.7, z: 0.08 },
    keywords: ["television", "tv", "flat screen", "screen"],
  },
  {
    id: "bench-01",
    name: "Bench",
    category: "living",
    modelUrl: `${ASSET_BASE}/bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.45, z: 0.4 },
    keywords: ["bench", "cushion bench", "entryway bench", "window bench"],
  },
  {
    id: "bar-stool-01",
    name: "Bar Stool",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/bar-stool-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.75, z: 0.4 },
    keywords: ["bar stool", "counter stool", "high stool", "stool"],
  },

  // ── Kitchen (additional) ──────────────────────────────────
  {
    id: "large-fridge-01",
    name: "Large Refrigerator",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/large-fridge-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 1.9, z: 0.75 },
    keywords: ["large fridge", "large refrigerator", "double door fridge", "french door fridge"],
  },
  {
    id: "microwave-01",
    name: "Microwave",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/microwave-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.3, z: 0.35 },
    keywords: ["microwave", "microwave oven"],
  },
  {
    id: "coffee-machine-01",
    name: "Coffee Machine",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/coffee-machine-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.35, z: 0.3 },
    keywords: ["coffee machine", "coffee maker", "espresso machine"],
  },
  {
    id: "electric-stove-01",
    name: "Electric Stove",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/electric-stove-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["electric stove", "electric range", "induction stove", "electric cooktop"],
  },
  {
    id: "toaster-01",
    name: "Toaster",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/toaster-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.2, z: 0.2 },
    keywords: ["toaster"],
  },

  // ── Bedroom (additional) ──────────────────────────────────
  {
    id: "bedside-table-01",
    name: "Bedside Table",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bedside-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.5, z: 0.4 },
    keywords: ["bedside table", "bedside cabinet", "side table"],
  },

  // ── Bathroom (additional) ─────────────────────────────────
  {
    id: "round-shower-01",
    name: "Round Shower",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/round-shower-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.95, y: 2.1, z: 0.95 },
    keywords: ["round shower", "circular shower", "corner shower"],
  },
  {
    id: "bathroom-cabinet-01",
    name: "Bathroom Cabinet",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/bathroom-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.7, z: 0.35 },
    keywords: ["bathroom cabinet", "medicine cabinet", "bathroom storage"],
  },
  {
    id: "bathroom-mirror-01",
    name: "Bathroom Mirror",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/bathroom-mirror-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.8, z: 0.05 },
    keywords: ["bathroom mirror", "mirror", "vanity mirror", "wall mirror"],
  },

  // ── Office (additional) ───────────────────────────────────
  {
    id: "monitor-01",
    name: "Monitor",
    category: "office",
    modelUrl: `${ASSET_BASE}/monitor-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.45, z: 0.2 },
    keywords: ["monitor", "computer screen", "display", "computer monitor"],
  },
  {
    id: "laptop-01",
    name: "Laptop",
    category: "office",
    modelUrl: `${ASSET_BASE}/laptop-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.35, y: 0.02, z: 0.25 },
    keywords: ["laptop", "notebook", "computer"],
  },

  // ── Utility ───────────────────────────────────────────────
  {
    id: "washing-machine-01",
    name: "Washing Machine",
    category: "utility",
    modelUrl: `${ASSET_BASE}/washing-machine-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["washing machine", "washer", "laundry machine"],
  },
  {
    id: "dryer-01",
    name: "Dryer",
    category: "utility",
    modelUrl: `${ASSET_BASE}/dryer-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["dryer", "tumble dryer", "clothes dryer"],
  },

  // ── Decor ─────────────────────────────────────────────────
  {
    id: "floor-lamp-01",
    name: "Floor Lamp",
    category: "decor",
    modelUrl: `${ASSET_BASE}/floor-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.35, y: 1.6, z: 0.35 },
    keywords: ["floor lamp", "standing lamp", "lamp", "tall lamp"],
  },
  {
    id: "table-lamp-01",
    name: "Table Lamp",
    category: "decor",
    modelUrl: `${ASSET_BASE}/table-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.2, y: 0.4, z: 0.2 },
    keywords: ["table lamp", "desk lamp", "bedside lamp"],
  },
  {
    id: "plant-01",
    name: "Potted Plant",
    category: "decor",
    modelUrl: `${ASSET_BASE}/plant-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.8, z: 0.4 },
    keywords: ["plant", "potted plant", "houseplant", "indoor plant"],
  },
  {
    id: "rug-01",
    name: "Rug",
    category: "decor",
    modelUrl: `${ASSET_BASE}/rug-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.0, y: 0.01, z: 1.4 },
    keywords: ["rug", "carpet", "area rug", "floor rug"],
  },

  // ── Living (batch 3) ──────────────────────────────────────
  {
    id: "recliner-01",
    name: "Recliner",
    category: "living",
    modelUrl: `${ASSET_BASE}/recliner-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 1.0, z: 0.9 },
    keywords: ["recliner", "reclining chair", "lazy boy", "lounge recliner"],
  },
  {
    id: "l-shaped-sofa-01",
    name: "L-Shaped Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/l-shaped-sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.8, y: 0.85, z: 2.8 },
    keywords: ["l-shaped sofa", "l shaped sofa", "l sofa", "sectional corner sofa"],
  },
  {
    id: "long-sofa-01",
    name: "Long Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/long-sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.8, y: 0.85, z: 0.9 },
    keywords: ["long sofa", "large sofa", "four seater sofa", "4 seater"],
  },
  {
    id: "ottoman-01",
    name: "Ottoman",
    category: "living",
    modelUrl: `${ASSET_BASE}/ottoman-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.7, y: 0.4, z: 0.7 },
    keywords: ["ottoman", "footrest", "pouf", "footstool"],
  },
  {
    id: "cushion-chair-01",
    name: "Cushion Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/cushion-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.85, z: 0.5 },
    keywords: ["cushion chair", "padded chair", "upholstered chair"],
  },
  {
    id: "rounded-chair-01",
    name: "Rounded Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/rounded-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.8, z: 0.6 },
    keywords: ["rounded chair", "barrel chair", "tub chair", "round chair"],
  },

  // ── Kitchen (batch 3) ─────────────────────────────────────
  {
    id: "modern-dining-chair-01",
    name: "Modern Dining Chair",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/modern-dining-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.85, z: 0.5 },
    keywords: ["modern dining chair", "modern chair", "cushioned dining chair"],
  },
  {
    id: "square-coffee-table-01",
    name: "Square Coffee Table",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/square-coffee-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.45, z: 0.8 },
    keywords: ["square coffee table", "square table", "small square table"],
  },
  {
    id: "glass-table-01",
    name: "Glass Table",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/glass-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.4, y: 0.75, z: 0.8 },
    keywords: ["glass table", "glass dining table", "transparent table"],
  },
  {
    id: "cloth-table-01",
    name: "Cloth Table",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/cloth-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.75, z: 0.8 },
    keywords: ["cloth table", "tablecloth table", "covered table"],
  },
  {
    id: "mini-fridge-01",
    name: "Mini Fridge",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/mini-fridge-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.85, z: 0.5 },
    keywords: ["mini fridge", "small fridge", "bar fridge", "compact fridge", "dorm fridge"],
  },

  // ── Bedroom (batch 3) ─────────────────────────────────────
  {
    id: "wide-bookcase-01",
    name: "Wide Bookcase",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/wide-bookcase-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 1.8, z: 0.35 },
    keywords: ["wide bookcase", "wide bookshelf", "large bookcase", "wide shelf"],
  },
  {
    id: "low-shelf-01",
    name: "Low Shelf",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/low-shelf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.8, z: 0.35 },
    keywords: ["low shelf", "low bookcase", "low bookshelf", "short shelf"],
  },
  {
    id: "bedroom-cabinet-01",
    name: "Bedroom Cabinet",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bedroom-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.9, z: 0.45 },
    keywords: ["bedroom cabinet", "storage cabinet", "linen cabinet"],
  },
  {
    id: "drawer-cabinet-01",
    name: "Drawer Cabinet",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/drawer-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.7, z: 0.4 },
    keywords: ["drawer cabinet", "chest of drawers", "dresser", "drawer chest"],
  },
  {
    id: "side-table-drawers-01",
    name: "Side Table with Drawers",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/side-table-drawers-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.55, z: 0.4 },
    keywords: ["side table drawers", "side table with drawers", "drawer side table", "end table"],
  },

  // ── Bathroom (batch 3) ────────────────────────────────────
  {
    id: "square-sink-01",
    name: "Square Sink",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/square-sink-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.5 },
    keywords: ["square sink", "square basin", "modern sink", "rectangular sink"],
  },
  {
    id: "square-toilet-01",
    name: "Square Toilet",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/square-toilet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.4, z: 0.65 },
    keywords: ["square toilet", "modern toilet", "wall hung toilet"],
  },

  // ── Decor (batch 3) ───────────────────────────────────────
  {
    id: "ceiling-fan-01",
    name: "Ceiling Fan",
    category: "decor",
    modelUrl: `${ASSET_BASE}/ceiling-fan-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.3, z: 1.2 },
    keywords: ["ceiling fan", "fan", "overhead fan"],
  },
  {
    id: "wall-lamp-01",
    name: "Wall Lamp",
    category: "decor",
    modelUrl: `${ASSET_BASE}/wall-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.15, y: 0.25, z: 0.2 },
    keywords: ["wall lamp", "sconce", "wall sconce", "wall light"],
  },
  {
    id: "square-floor-lamp-01",
    name: "Square Floor Lamp",
    category: "decor",
    modelUrl: `${ASSET_BASE}/square-floor-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 1.6, z: 0.3 },
    keywords: ["square floor lamp", "modern floor lamp", "square lamp"],
  },
  {
    id: "round-rug-01",
    name: "Round Rug",
    category: "decor",
    modelUrl: `${ASSET_BASE}/round-rug-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.01, z: 1.8 },
    keywords: ["round rug", "circular rug", "round carpet", "circle rug"],
  },
  {
    id: "square-rug-01",
    name: "Square Rug",
    category: "decor",
    modelUrl: `${ASSET_BASE}/square-rug-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.0, y: 0.01, z: 2.0 },
    keywords: ["square rug", "square carpet", "area rug square"],
  },
  {
    id: "trashcan-01",
    name: "Trash Can",
    category: "decor",
    modelUrl: `${ASSET_BASE}/trashcan-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.6, z: 0.3 },
    keywords: ["trash can", "trashcan", "garbage bin", "waste bin", "bin"],
  },
  {
    id: "coat-rack-01",
    name: "Coat Rack",
    category: "decor",
    modelUrl: `${ASSET_BASE}/coat-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 1.8, z: 0.5 },
    keywords: ["coat rack", "coat stand", "hat rack", "coat hanger stand"],
  },

  // ── Outdoor ─────────────────────────────────────────────────
  {
    id: "patio-chair-01",
    name: "Patio Chair",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/dining-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["patio chair", "outdoor chair", "garden chair", "patio"],
  },
  {
    id: "garden-table-01",
    name: "Garden Table",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/round-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.75, z: 1.2 },
    keywords: ["garden table", "outdoor table", "patio table"],
  },
  {
    id: "outdoor-bench-01",
    name: "Outdoor Bench",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.45, z: 0.5 },
    keywords: ["outdoor bench", "garden bench", "park bench"],
  },
  {
    id: "planter-01",
    name: "Planter",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/plant-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.6, z: 0.5 },
    keywords: ["planter", "flower pot", "garden planter", "outdoor planter"],
  },
  {
    id: "sun-lounger-01",
    name: "Sun Lounger",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.7, y: 0.4, z: 1.9 },
    keywords: ["sun lounger", "lounger", "chaise longue", "deck chair", "sunbed"],
  },
  {
    id: "picnic-table-01",
    name: "Picnic Table",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/dining-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.75, z: 1.4 },
    keywords: ["picnic table", "picnic", "outdoor dining table"],
  },

  // ── Garage ──────────────────────────────────────────────────
  {
    id: "workbench-01",
    name: "Workbench",
    category: "garage",
    modelUrl: `${ASSET_BASE}/desk-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.9, z: 0.7 },
    keywords: ["workbench", "work bench", "garage bench", "workshop bench"],
  },
  {
    id: "tool-cabinet-01",
    name: "Tool Cabinet",
    category: "garage",
    modelUrl: `${ASSET_BASE}/wardrobe-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 1.8, z: 0.5 },
    keywords: ["tool cabinet", "tool chest", "tool storage", "garage cabinet"],
  },
  {
    id: "storage-shelf-01",
    name: "Storage Shelf",
    category: "garage",
    modelUrl: `${ASSET_BASE}/bookshelf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 1.8, z: 0.5 },
    keywords: ["storage shelf", "garage shelf", "utility shelf", "metal shelf"],
  },

  // ── Living (additional) ─────────────────────────────────────
  {
    id: "sectional-sofa-01",
    name: "Sectional Sofa",
    category: "living",
    modelUrl: `${ASSET_BASE}/sectional-sofa-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 3.0, y: 0.85, z: 1.8 },
    keywords: ["sectional sofa", "l-shaped sofa", "corner sofa"],
  },
  {
    id: "recliner-02",
    name: "Recliner Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/recliner-02.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 1.0, z: 0.9 },
    keywords: ["recliner", "reclining chair", "lazy boy"],
  },
  {
    id: "media-cabinet-01",
    name: "Media Cabinet",
    category: "living",
    modelUrl: `${ASSET_BASE}/media-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.6, z: 0.45 },
    keywords: ["media cabinet", "media unit", "av cabinet"],
  },
  {
    id: "side-table-02",
    name: "Side Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/side-table-02.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.55, z: 0.5 },
    keywords: ["side table", "end table", "lamp table"],
  },
  {
    id: "accent-chair-01",
    name: "Accent Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/accent-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.75, y: 0.8, z: 0.75 },
    keywords: ["accent chair", "feature chair", "statement chair"],
  },
  {
    id: "bean-bag-01",
    name: "Bean Bag",
    category: "living",
    modelUrl: `${ASSET_BASE}/bean-bag-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 0.7, z: 0.9 },
    keywords: ["bean bag", "beanbag", "floor cushion"],
  },
  {
    id: "console-table-01",
    name: "Console Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/console-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.8, z: 0.35 },
    keywords: ["console table", "hall table", "entry table"],
  },
  {
    id: "wall-shelf-01",
    name: "Wall Shelf",
    category: "living",
    modelUrl: `${ASSET_BASE}/wall-shelf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.3, z: 0.25 },
    keywords: ["wall shelf", "floating shelf", "display shelf"],
  },
  {
    id: "room-divider-01",
    name: "Room Divider",
    category: "living",
    modelUrl: `${ASSET_BASE}/room-divider-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 1.8, z: 0.3 },
    keywords: ["room divider", "screen", "partition"],
  },
  {
    id: "pouf-01",
    name: "Pouf",
    category: "living",
    modelUrl: `${ASSET_BASE}/pouf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.4, z: 0.5 },
    keywords: ["pouf", "ottoman", "footrest"],
  },
  {
    id: "lounge-chair-01",
    name: "Lounge Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/lounge-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.75, z: 0.85 },
    keywords: ["lounge chair", "reading chair", "club chair"],
  },
  {
    id: "curtain-rod-01",
    name: "Curtain Rod",
    category: "living",
    modelUrl: `${ASSET_BASE}/curtain-rod-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.0, y: 0.05, z: 0.05 },
    keywords: ["curtain rod", "curtain pole", "drape rod"],
  },
  {
    id: "area-rug-large-01",
    name: "Large Area Rug",
    category: "living",
    modelUrl: `${ASSET_BASE}/area-rug-large-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 3.0, y: 0.02, z: 2.0 },
    keywords: ["area rug", "large rug", "carpet", "floor rug"],
  },
  {
    id: "throw-blanket-01",
    name: "Throw Blanket",
    category: "living",
    modelUrl: `${ASSET_BASE}/throw-blanket-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.05, z: 1.0 },
    keywords: ["throw blanket", "throw", "blanket"],
  },

  // ── Bedroom (additional) ────────────────────────────────────
  {
    id: "bunk-bed-01",
    name: "Bunk Bed",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bunk-bed-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 1.8, z: 2.0 },
    keywords: ["bunk bed", "bunk", "double decker bed"],
  },
  {
    id: "canopy-bed-01",
    name: "Canopy Bed",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/canopy-bed-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.6, y: 2.2, z: 2.1 },
    keywords: ["canopy bed", "four poster bed", "poster bed"],
  },
  {
    id: "shoe-rack-01",
    name: "Shoe Rack",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/shoe-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.6, z: 0.3 },
    keywords: ["shoe rack", "shoe shelf", "shoe organizer"],
  },
  {
    id: "bedside-lamp-01",
    name: "Bedside Lamp",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/bedside-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.2, y: 0.45, z: 0.2 },
    keywords: ["bedside lamp", "table lamp", "night lamp"],
  },
  {
    id: "vanity-table-01",
    name: "Vanity Table",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/vanity-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.75, z: 0.45 },
    keywords: ["vanity table", "dressing table", "makeup table"],
  },
  {
    id: "clothes-hanger-01",
    name: "Clothes Hanger Stand",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/clothes-hanger-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 1.7, z: 0.5 },
    keywords: ["clothes hanger", "coat stand", "hat stand"],
  },
  {
    id: "storage-bench-01",
    name: "Storage Bench",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/storage-bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.5, z: 0.4 },
    keywords: ["storage bench", "ottoman bench", "end of bed bench"],
  },
  {
    id: "blanket-chest-01",
    name: "Blanket Chest",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/blanket-chest-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.5, z: 0.45 },
    keywords: ["blanket chest", "hope chest", "storage chest"],
  },
  {
    id: "jewelry-box-01",
    name: "Jewelry Box",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/jewelry-box-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.15, z: 0.2 },
    keywords: ["jewelry box", "trinket box", "keepsake box"],
  },
  {
    id: "linen-cabinet-01",
    name: "Linen Cabinet",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/linen-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 1.8, z: 0.4 },
    keywords: ["linen cabinet", "linen closet", "towel cabinet"],
  },

  // ── Kitchen (additional) ────────────────────────────────────
  {
    id: "dishwasher-01",
    name: "Dishwasher",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/dishwasher-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.85, z: 0.6 },
    keywords: ["dishwasher", "dish washer"],
  },
  {
    id: "kitchen-island-01",
    name: "Kitchen Island",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/kitchen-island-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.9, z: 0.8 },
    keywords: ["kitchen island", "island counter", "prep island"],
  },
  {
    id: "spice-rack-01",
    name: "Spice Rack",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/spice-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.4, z: 0.1 },
    keywords: ["spice rack", "spice shelf", "seasoning rack"],
  },
  {
    id: "trash-can-01",
    name: "Trash Can",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/trash-can-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.7, z: 0.3 },
    keywords: ["trash can", "bin", "garbage can", "waste bin", "rubbish bin"],
  },
  {
    id: "blender-01",
    name: "Blender",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/blender-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.2, y: 0.4, z: 0.2 },
    keywords: ["blender", "food processor", "mixer"],
  },
  {
    id: "coffee-maker-01",
    name: "Coffee Maker",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/coffee-maker-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.35, z: 0.2 },
    keywords: ["coffee maker", "coffee machine", "espresso machine"],
  },
  {
    id: "pot-rack-01",
    name: "Pot Rack",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/pot-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.4, z: 0.4 },
    keywords: ["pot rack", "pan rack", "hanging rack"],
  },
  {
    id: "range-hood-01",
    name: "Range Hood",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/range-hood-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 0.5, z: 0.5 },
    keywords: ["range hood", "extractor", "exhaust hood", "vent hood"],
  },
  {
    id: "cutting-board-01",
    name: "Cutting Board",
    category: "kitchen",
    modelUrl: `${ASSET_BASE}/cutting-board-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.03, z: 0.3 },
    keywords: ["cutting board", "chopping board"],
  },

  // ── Bathroom (additional) ───────────────────────────────────
  {
    id: "towel-rack-01",
    name: "Towel Rack",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/towel-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.8, z: 0.15 },
    keywords: ["towel rack", "towel rail", "towel bar", "towel holder"],
  },
  {
    id: "medicine-cabinet-01",
    name: "Medicine Cabinet",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/medicine-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.6, z: 0.15 },
    keywords: ["medicine cabinet", "bathroom cabinet", "wall cabinet"],
  },
  {
    id: "bath-mat-01",
    name: "Bath Mat",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/bath-mat-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.02, z: 0.5 },
    keywords: ["bath mat", "bathroom rug", "floor mat"],
  },
  {
    id: "laundry-basket-01",
    name: "Laundry Basket",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/laundry-basket-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.6, z: 0.35 },
    keywords: ["laundry basket", "hamper", "clothes basket"],
  },
  {
    id: "soap-dispenser-01",
    name: "Soap Dispenser",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/soap-dispenser-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.08, y: 0.2, z: 0.08 },
    keywords: ["soap dispenser", "hand soap", "pump dispenser"],
  },
  {
    id: "bathroom-scale-01",
    name: "Bathroom Scale",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/bathroom-scale-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.05, z: 0.3 },
    keywords: ["bathroom scale", "weight scale", "digital scale"],
  },
  {
    id: "toilet-paper-holder-01",
    name: "Toilet Paper Holder",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/toilet-paper-holder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.15, y: 0.15, z: 0.1 },
    keywords: ["toilet paper holder", "tp holder", "roll holder"],
  },
  {
    id: "wall-mirror-01",
    name: "Wall Mirror",
    category: "bathroom",
    modelUrl: `${ASSET_BASE}/wall-mirror-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.8, z: 0.05 },
    keywords: ["wall mirror", "bathroom mirror", "vanity mirror", "mirror"],
  },

  // ── Office (additional) ─────────────────────────────────────
  {
    id: "standing-desk-01",
    name: "Standing Desk",
    category: "office",
    modelUrl: `${ASSET_BASE}/standing-desk-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.4, y: 1.1, z: 0.7 },
    keywords: ["standing desk", "sit-stand desk", "adjustable desk"],
  },
  {
    id: "monitor-stand-01",
    name: "Monitor Stand",
    category: "office",
    modelUrl: `${ASSET_BASE}/monitor-stand-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.15, z: 0.25 },
    keywords: ["monitor stand", "monitor riser", "screen stand"],
  },
  {
    id: "printer-01",
    name: "Printer",
    category: "office",
    modelUrl: `${ASSET_BASE}/printer-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.45, y: 0.3, z: 0.4 },
    keywords: ["printer", "laser printer", "inkjet printer"],
  },
  {
    id: "whiteboard-01",
    name: "Whiteboard",
    category: "office",
    modelUrl: `${ASSET_BASE}/whiteboard-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.9, z: 0.05 },
    keywords: ["whiteboard", "dry erase board", "marker board"],
  },
  {
    id: "desk-lamp-01",
    name: "Desk Lamp",
    category: "office",
    modelUrl: `${ASSET_BASE}/desk-lamp-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.2, y: 0.45, z: 0.2 },
    keywords: ["desk lamp", "task lamp", "reading lamp", "study lamp"],
  },
  {
    id: "paper-shredder-01",
    name: "Paper Shredder",
    category: "office",
    modelUrl: `${ASSET_BASE}/paper-shredder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.35, y: 0.5, z: 0.25 },
    keywords: ["paper shredder", "shredder", "document shredder"],
  },
  {
    id: "file-organizer-01",
    name: "File Organizer",
    category: "office",
    modelUrl: `${ASSET_BASE}/file-organizer-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.35, y: 0.3, z: 0.25 },
    keywords: ["file organizer", "desk organizer", "paper tray"],
  },
  {
    id: "keyboard-tray-01",
    name: "Keyboard Tray",
    category: "office",
    modelUrl: `${ASSET_BASE}/keyboard-tray-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.65, y: 0.05, z: 0.3 },
    keywords: ["keyboard tray", "keyboard shelf", "keyboard drawer"],
  },
  {
    id: "ergonomic-chair-01",
    name: "Ergonomic Chair",
    category: "office",
    modelUrl: `${ASSET_BASE}/ergonomic-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.65, y: 1.2, z: 0.65 },
    keywords: ["ergonomic chair", "task chair", "mesh chair"],
  },
  {
    id: "conference-table-01",
    name: "Conference Table",
    category: "office",
    modelUrl: `${ASSET_BASE}/conference-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.4, y: 0.75, z: 1.2 },
    keywords: ["conference table", "meeting table", "boardroom table"],
  },

  // ── Dining (additional) ─────────────────────────────────────
  {
    id: "buffet-table-01",
    name: "Buffet Table",
    category: "living",
    modelUrl: `${ASSET_BASE}/buffet-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.6, y: 0.85, z: 0.5 },
    keywords: ["buffet table", "sideboard", "credenza"],
  },
  {
    id: "china-cabinet-01",
    name: "China Cabinet",
    category: "living",
    modelUrl: `${ASSET_BASE}/china-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 1.8, z: 0.4 },
    keywords: ["china cabinet", "display cabinet", "hutch", "curio cabinet"],
  },
  {
    id: "wine-rack-01",
    name: "Wine Rack",
    category: "living",
    modelUrl: `${ASSET_BASE}/wine-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 1.0, z: 0.3 },
    keywords: ["wine rack", "wine storage", "bottle rack"],
  },
  {
    id: "serving-cart-01",
    name: "Serving Cart",
    category: "living",
    modelUrl: `${ASSET_BASE}/serving-cart-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.8, z: 0.45 },
    keywords: ["serving cart", "bar cart", "drinks trolley", "tea cart"],
  },
  {
    id: "bar-cabinet-01",
    name: "Bar Cabinet",
    category: "living",
    modelUrl: `${ASSET_BASE}/bar-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 1.1, z: 0.45 },
    keywords: ["bar cabinet", "drinks cabinet", "liquor cabinet"],
  },
  {
    id: "high-chair-01",
    name: "High Chair",
    category: "living",
    modelUrl: `${ASSET_BASE}/high-chair-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.9, z: 0.5 },
    keywords: ["high chair", "baby chair", "feeding chair"],
  },
  {
    id: "bench-seat-01",
    name: "Bench Seat",
    category: "living",
    modelUrl: `${ASSET_BASE}/bench-seat-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.45, z: 0.4 },
    keywords: ["bench seat", "dining bench", "long bench"],
  },
  {
    id: "lazy-susan-01",
    name: "Lazy Susan",
    category: "living",
    modelUrl: `${ASSET_BASE}/lazy-susan-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.05, z: 0.4 },
    keywords: ["lazy susan", "turntable", "revolving tray"],
  },

  // ── Outdoor (additional) ────────────────────────────────────
  {
    id: "garden-bench-01",
    name: "Garden Bench",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/garden-bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.5, y: 0.85, z: 0.55 },
    keywords: ["garden bench", "park bench", "outdoor bench"],
  },
  {
    id: "patio-table-01",
    name: "Patio Table",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/patio-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.75, z: 1.2 },
    keywords: ["patio table", "outdoor table", "garden table"],
  },
  {
    id: "lounge-chair-outdoor-01",
    name: "Outdoor Lounge Chair",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/lounge-chair-outdoor-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.8, z: 0.7 },
    keywords: ["outdoor lounge", "sun lounger", "deck chair", "chaise longue"],
  },
  {
    id: "planter-box-01",
    name: "Planter Box",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/planter-box-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.6, y: 0.5, z: 0.3 },
    keywords: ["planter box", "flower box", "garden planter", "plant pot"],
  },
  {
    id: "grill-01",
    name: "Grill",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/grill-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 1.0, z: 0.6 },
    keywords: ["grill", "bbq", "barbecue", "outdoor grill"],
  },
  {
    id: "umbrella-01",
    name: "Patio Umbrella",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/umbrella-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.1, y: 2.2, z: 0.1 },
    keywords: ["patio umbrella", "parasol", "sun umbrella", "garden umbrella"],
  },
  {
    id: "hammock-stand-01",
    name: "Hammock Stand",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/hammock-stand-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 3.0, y: 1.2, z: 1.0 },
    keywords: ["hammock stand", "hammock frame", "hammock"],
  },
  {
    id: "fire-pit-01",
    name: "Fire Pit",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/fire-pit-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.5, z: 0.8 },
    keywords: ["fire pit", "firepit", "outdoor fire", "fire bowl"],
  },
  {
    id: "bird-bath-01",
    name: "Bird Bath",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/bird-bath-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.8, z: 0.5 },
    keywords: ["bird bath", "birdbath", "garden ornament"],
  },
  {
    id: "garden-light-01",
    name: "Garden Light",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/garden-light-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.15, y: 0.6, z: 0.15 },
    keywords: ["garden light", "path light", "landscape light", "solar light"],
  },
  {
    id: "swing-set-01",
    name: "Swing Set",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/swing-set-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.5, y: 2.0, z: 1.5 },
    keywords: ["swing set", "swing", "garden swing", "porch swing"],
  },
  {
    id: "outdoor-rug-01",
    name: "Outdoor Rug",
    category: "outdoor",
    modelUrl: `${ASSET_BASE}/outdoor-rug-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 2.0, y: 0.02, z: 1.5 },
    keywords: ["outdoor rug", "patio rug", "deck rug"],
  },

  // ── Decor ───────────────────────────────────────────────────
  {
    id: "wall-art-01",
    name: "Wall Art",
    category: "decor",
    modelUrl: `${ASSET_BASE}/wall-art-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.6, z: 0.03 },
    keywords: ["wall art", "painting", "artwork", "canvas art", "picture"],
  },
  {
    id: "vase-01",
    name: "Vase",
    category: "decor",
    modelUrl: `${ASSET_BASE}/vase-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.15, y: 0.35, z: 0.15 },
    keywords: ["vase", "flower vase", "decorative vase"],
  },
  {
    id: "candle-holder-01",
    name: "Candle Holder",
    category: "decor",
    modelUrl: `${ASSET_BASE}/candle-holder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.1, y: 0.25, z: 0.1 },
    keywords: ["candle holder", "candlestick", "candelabra"],
  },
  {
    id: "photo-frame-01",
    name: "Photo Frame",
    category: "decor",
    modelUrl: `${ASSET_BASE}/photo-frame-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.3, z: 0.05 },
    keywords: ["photo frame", "picture frame", "frame"],
  },
  {
    id: "wall-clock-01",
    name: "Wall Clock",
    category: "decor",
    modelUrl: `${ASSET_BASE}/wall-clock-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.3, z: 0.05 },
    keywords: ["wall clock", "clock", "timepiece"],
  },
  {
    id: "sculpture-01",
    name: "Sculpture",
    category: "decor",
    modelUrl: `${ASSET_BASE}/sculpture-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.5, z: 0.3 },
    keywords: ["sculpture", "statue", "figurine", "art piece"],
  },
  {
    id: "flower-arrangement-01",
    name: "Flower Arrangement",
    category: "decor",
    modelUrl: `${ASSET_BASE}/flower-arrangement-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 0.4, z: 0.3 },
    keywords: ["flower arrangement", "bouquet", "floral arrangement", "flowers"],
  },
  {
    id: "globe-01",
    name: "Globe",
    category: "decor",
    modelUrl: `${ASSET_BASE}/globe-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.35, z: 0.25 },
    keywords: ["globe", "world globe", "desk globe"],
  },
  {
    id: "terrarium-01",
    name: "Terrarium",
    category: "decor",
    modelUrl: `${ASSET_BASE}/terrarium-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.2, y: 0.3, z: 0.2 },
    keywords: ["terrarium", "plant terrarium", "glass terrarium"],
  },
  {
    id: "incense-holder-01",
    name: "Incense Holder",
    category: "decor",
    modelUrl: `${ASSET_BASE}/incense-holder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.05, z: 0.05 },
    keywords: ["incense holder", "incense burner", "incense tray"],
  },

  // ── Utility (additional) ────────────────────────────────────
  {
    id: "ironing-board-01",
    name: "Ironing Board",
    category: "utility",
    modelUrl: `${ASSET_BASE}/ironing-board-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.9, z: 0.35 },
    keywords: ["ironing board", "iron board", "pressing board"],
  },
  {
    id: "vacuum-01",
    name: "Vacuum Cleaner",
    category: "utility",
    modelUrl: `${ASSET_BASE}/vacuum-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.3, y: 1.1, z: 0.3 },
    keywords: ["vacuum cleaner", "vacuum", "hoover"],
  },
  {
    id: "mop-bucket-01",
    name: "Mop Bucket",
    category: "utility",
    modelUrl: `${ASSET_BASE}/mop-bucket-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.4, y: 0.35, z: 0.3 },
    keywords: ["mop bucket", "cleaning bucket", "mop pail"],
  },
  {
    id: "tool-chest-01",
    name: "Tool Chest",
    category: "utility",
    modelUrl: `${ASSET_BASE}/tool-chest-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.7, y: 0.5, z: 0.4 },
    keywords: ["tool chest", "tool box", "tool cabinet"],
  },
  {
    id: "step-ladder-01",
    name: "Step Ladder",
    category: "utility",
    modelUrl: `${ASSET_BASE}/step-ladder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 1.5, z: 0.7 },
    keywords: ["step ladder", "ladder", "folding ladder", "stepladder"],
  },
  {
    id: "storage-bin-01",
    name: "Storage Bin",
    category: "utility",
    modelUrl: `${ASSET_BASE}/storage-bin-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.5, y: 0.4, z: 0.35 },
    keywords: ["storage bin", "storage box", "container", "crate"],
  },
  {
    id: "shoe-cabinet-01",
    name: "Shoe Cabinet",
    category: "utility",
    modelUrl: `${ASSET_BASE}/shoe-cabinet-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 1.0, z: 0.35 },
    keywords: ["shoe cabinet", "shoe cupboard", "shoe storage", "entryway cabinet"],
  },
  {
    id: "key-holder-01",
    name: "Key Holder",
    category: "utility",
    modelUrl: `${ASSET_BASE}/key-holder-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.25, y: 0.15, z: 0.05 },
    keywords: ["key holder", "key rack", "key hooks", "key organizer"],
  },

  // ── Kids ────────────────────────────────────────────────────
  {
    id: "crib-01",
    name: "Crib",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/crib-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.3, y: 1.0, z: 0.7 },
    keywords: ["crib", "baby crib", "cot", "baby bed", "infant bed"],
  },
  {
    id: "toy-box-01",
    name: "Toy Box",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/toy-box-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.5, z: 0.5 },
    keywords: ["toy box", "toy chest", "toy storage", "play box"],
  },
  {
    id: "kids-desk-01",
    name: "Kids Desk",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/kids-desk-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 0.6, z: 0.5 },
    keywords: ["kids desk", "children desk", "study desk", "homework desk"],
  },
  {
    id: "rocking-horse-01",
    name: "Rocking Horse",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/rocking-horse-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.7, y: 0.7, z: 0.3 },
    keywords: ["rocking horse", "toy horse", "ride on"],
  },
  {
    id: "kids-bookshelf-01",
    name: "Kids Bookshelf",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/kids-bookshelf-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.8, y: 1.0, z: 0.3 },
    keywords: ["kids bookshelf", "children bookcase", "toy shelf"],
  },
  {
    id: "changing-table-01",
    name: "Changing Table",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/changing-table-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 0.9, y: 0.9, z: 0.55 },
    keywords: ["changing table", "baby changer", "nappy station", "diaper station"],
  },
  {
    id: "play-tent-01",
    name: "Play Tent",
    category: "bedroom",
    modelUrl: `${ASSET_BASE}/play-tent-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 1.2, z: 1.2 },
    keywords: ["play tent", "teepee", "kids tent", "play house"],
  },

  // ── Gym ─────────────────────────────────────────────────────
  {
    id: "treadmill-01",
    name: "Treadmill",
    category: "utility",
    modelUrl: `${ASSET_BASE}/treadmill-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 1.4, z: 0.8 },
    keywords: ["treadmill", "running machine", "exercise treadmill"],
  },
  {
    id: "dumbbell-rack-01",
    name: "Dumbbell Rack",
    category: "utility",
    modelUrl: `${ASSET_BASE}/dumbbell-rack-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 0.8, z: 0.5 },
    keywords: ["dumbbell rack", "weight rack", "free weight rack"],
  },
  {
    id: "yoga-mat-01",
    name: "Yoga Mat",
    category: "utility",
    modelUrl: `${ASSET_BASE}/yoga-mat-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.8, y: 0.02, z: 0.6 },
    keywords: ["yoga mat", "exercise mat", "fitness mat", "workout mat"],
  },
  {
    id: "exercise-bike-01",
    name: "Exercise Bike",
    category: "utility",
    modelUrl: `${ASSET_BASE}/exercise-bike-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.0, y: 1.2, z: 0.5 },
    keywords: ["exercise bike", "stationary bike", "spin bike", "cycling machine"],
  },
  {
    id: "weight-bench-01",
    name: "Weight Bench",
    category: "utility",
    modelUrl: `${ASSET_BASE}/weight-bench-01.glb`,
    thumbnailUrl: null,
    dimensions: { x: 1.2, y: 0.5, z: 0.45 },
    keywords: ["weight bench", "workout bench", "press bench", "gym bench"],
  },
];

export const FURNITURE_CATALOG: CatalogItem[] = FURNITURE_CATALOG_SEED.map(withCatalogDefaults);

/**
 * Fuzzy-match an item name (e.g. from Gemini output) against catalog keywords.
 * Priority: exact keyword match → substring match → null.
 */
export function matchCatalogItem(name: string): CatalogItem | null {
  const lower = name.toLowerCase().trim();
  if (!lower) return null;

  // 1. Exact keyword match
  for (const item of FURNITURE_CATALOG) {
    if (item.keywords.some((kw) => kw === lower)) {
      return item;
    }
  }

  // 2. Partial / substring match (keyword found within the name, or name found within keyword)
  for (const item of FURNITURE_CATALOG) {
    if (item.keywords.some((kw) => lower.includes(kw) || kw.includes(lower))) {
      return item;
    }
  }

  return null;
}
